name: build
on:
  push:
    branches: [master, ovirt-engine-4.5*]
  pull_request:
    branches: [master, ovirt-engine-4.5*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream
            pip-command: pip3

    name: el9stream

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:el9stream

    steps:
    - name: Install required PyPI packages
      run: pip3 install "ansible-lint>=6.0.0,<7.0.0"

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Create DNF repository
      run: |
        createrepo_c $ARTIFACTS_DIR
